In [5]:
import numpy as np
arr1=np.random.randint(1,9,(3,3))
arr2=np.random.randint(1,9,(3,3))
print("Array I : \n",arr1)
print("Array II : \n",arr2)
print("Multiplication : \n",np.multiply(arr1,arr2))
print("Product : \n",np.prod([arr1,arr2]))
print("Dot : \n", np.dot(arr1,arr2))

Array I : 
 [[1 7 7]
 [5 7 1]
 [5 5 7]]
Array II : 
 [[4 1 2]
 [4 1 5]
 [1 5 2]]
Multiplication : 
 [[ 4  7 14]
 [20  7  5]
 [ 5 25 14]]
Product : 
 480200000
Dot : 
 [[39 43 51]
 [49 17 47]
 [47 45 49]]


In [7]:
import numpy as np
arr1=np.array([5,6,7,8,9])
arr2=np.array([7,8,9,10])
print("Union : \n",np.union1d(arr1, arr2))
print("Intersection : \n",np.intersect1d(arr1, arr2, assume_unique=True))
print("Set Difference : \n",np.setdiff1d(arr1, arr2, assume_unique=True))
print("XOR : \n",np.setxor1d(arr1,arr2))

Union : 
 [ 5  6  7  8  9 10]
Intersection : 
 [7 8 9]
Set Difference : 
 [5 6]
XOR : 
 [ 5  6 10]


In [16]:
import numpy as np
x = np.random.randint(1,10, size=(1,8))
print("Cumulative Sum:",np.cumsum(x))
print("Cumulative Product:",np.cumprod(x))
print("Discrete Difference:",np.diff(x))
print("Unique:",np.unique(x))

Cumulative Sum: [ 7 15 23 25 32 41 46 48]
Cumulative Product: [     7     56    448    896   6272  56448 282240 564480]
Discrete Difference: [[ 1  0 -6  5  2 -4 -3]]
Unique: [2 5 7 8 9]


In [25]:
import numpy as np
z=[]
def sum(x, y):
  return x+y
arr1=np.array([5,6,7,8,9])
print("Array I :",arr1)
arr2=np.array([7,8,9,10,0])
print("Array II :",arr2)
for i, j in zip(arr1, arr2):
  z.append(i + j)
print("Zip() :",z)
arr3=np.add(arr1,arr2)
print("Add() :",arr3)
sum = np.frompyfunc(sum, 2, 1)
print("FromPyFunc() :",sum(arr1, arr2))

Array I : [5 6 7 8 9]
Array II : [ 7  8  9 10  0]
Zip() : [12, 14, 16, 18, 9]
Add() : [12 14 16 18  9]
FromPyFunc() : [12 14 16 18 9]


In [33]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(arr)
print("LCM using reduce() : ",np.lcm.reduce(arr))
print("HCF using reduce() : ",np.gcd.reduce(arr))

[[ 1  2  3  4  5  6  7  8  9 10]]
LCM using reduce() :  [ 1  2  3  4  5  6  7  8  9 10]
HCF using reduce() :  [ 1  2  3  4  5  6  7  8  9 10]
